name = "myslotmate"
type = "javascript"
compatibility_date = "2024-12-16"

[env.production]
routes = [
  { pattern = "example.com/*", zone_name = "example.com" }
]

[build]
command = "pnpm run build"
cwd = "./"
watch_paths = ["src/**/*.tsx", "src/**/*.ts"]

[build.upload]
format = "service-worker"
