import Hero from "./Hero";
import people from "./people";
import Trending from "./Trending";
import Banner from "./Banner";
import TrendingCard from "./TrendingCard";
import Idea from "./Idea";
import Footer from "./Footer";
import AllHosts from "./AllHosts";
import ShowcaseSections from "./ShowcaseSections";
export {Hero,people,Trending,Banner,TrendingCard,Idea,Footer,AllHosts,ShowcaseSections};
